**Importing the dataset**

In [10]:
import pandas as pd
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',header=None)
data.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [0]:
#from sklearn.datasets import load_iris

In [0]:
data_cp=data.copy()
X=data_cp[[0,1,2,3]]

In [0]:
#iris_dataset=load_iris()

In [18]:
data_cp[4].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [0]:
unique_val=list(data_cp[4].unique())

unique_dict={}
for i,j in enumerate(unique_val):
  unique_dict[j]=i


**Understanding the dataset**

In [22]:
unique_dict

{'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}

In [0]:
data_cp[4]=data_cp[4].map(unique_dict)

In [0]:
y=data_cp[4]

In [3]:
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))

Keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [117]:
print(iris_dataset['DESCR'][:200]+ "\n...")

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes
...


In [118]:
print("target names: \n{}".format(iris_dataset['target_names']))

target names: 
['setosa' 'versicolor' 'virginica']


In [119]:
print("feature names:\n {}".format(iris_dataset['feature_names']))

feature names:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [120]:
print("Type of data:\n {}".format(type(iris_dataset['data'])))

Type of data:
 <class 'numpy.ndarray'>


In [121]:
print("shape of data:\n {}".format(iris_dataset['data'].shape))

shape of data:
 (150, 4)


In [122]:
print("First 10 rows of data:\n {}".format(iris_dataset['data'][:10]))

First 10 rows of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [123]:
print("Type of target:\n {}".format(type(iris_dataset['target'])))

Type of target:
 <class 'numpy.ndarray'>


In [124]:
print("shape of target:\n {}".format(iris_dataset['target'].shape))

shape of target:
 (150,)


In [125]:
print("Target:\n {}".format(iris_dataset['target']))

Target:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


**Splitting data into train and test**

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
Xtr,Xte,ytr,yte=train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

In [129]:
print("X training data shape: {}".format(Xtr.shape))
print("y training data shape: {}".format(ytr.shape))
print("X test data shape: {}".format(Xte.shape))
print("y test data shape: {}".format(yte.shape))

X training data shape: (112, 4)
y training data shape: (112,)
X test data shape: (38, 4)
y test data shape: (38,)


**Understanding training  data**

In [33]:
import pandas as pd
iris_dataframe=pd.DataFrame(Xtr,columns=iris_dataset.feature_names)

NameError: ignored

In [32]:
pd.plotting.scatter_matrix(iris_dataframe,c=ytr,figsize=(10,10),diagonal='kde',marker='o',hist_kwds={'bins':20},s=60,alpha=.9)

NameError: ignored

**Applying the Model**

In [0]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [133]:
knn.fit(Xtr,ytr)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

**Checking the model on user test data value**

In [136]:
import numpy as np
Xnew=np.array([[5,2.9,1,0.2]])
print("Xnew.shape: {}".format(Xnew.shape))

Xnew.shape: (1, 4)


In [137]:
pred=knn.predict(Xnew)
print("Prediction : {}".format(pred))
print("Predicted target name: {}".format(iris_dataset['target_names'][pred]))

Prediction : [0]
Predicted target name: ['setosa']


In [138]:
ypred=knn.predict(Xte)
print("Test set predictions\n {}".format(ypred))

Test set predictions
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


**Checking the model on the test data set**

In [0]:
print("Test set score: {:.2f}".format(np.mean(ypred==yte)))

Test set score: 0.97


In [0]:
print("test set score: {:.2f}".format(knn.score(Xte,yte)))

test set score: 0.97


In [106]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(yte,ypred)
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

In [35]:
import matplotlib.pyplot as plt
plt.imshow(cm, interpolation='nearest',cmap=plt.cm.Blues)
tick_marks = np.arange(3);
plt.xticks(tick_marks, ['C','B','A'], rotation=45)
plt.yticks(tick_marks, ['C','B','A']);
fmt='d'
thresh=cnf_matrix.max() / 2.
for i, j in itertools.product(range(cnf_matrix.shape[0]), range(cnf_matrix.shape[1])):
        plt.text(j, i, format(cnf_matrix[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cnf_matrix[i, j] > thresh else "black")

NameError: ignored